### ISSUE TITLE
all the deposited samples from  "Seafloor Basalts"  paper seems to be the same (!)

### ISSUE THREAD

**Issue by matrs** [AstrobioMike/AstrobioMike.github.io#11]
Hey, hello Mike,
I was checking your dada2 microbiome tutorial and I started to play with the full data set from your [paper](https://www.frontiersin.org/articles/10.3389/fmicb.2015.01470/full):
The thing is that I downloaded all the files and after running some steps in my pipeline (qiime2/dada2), I got that every single sample has the **exact same microbial composition**. So I went and checked  all the downloaded files and as far I can tell, they all are the same (!). I got them from [NCBI](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA295345) and [ENA](https://www.ebi.ac.uk/ena/data/view/PRJNA295345) to be sure about it. Just a few as an example:

`seqkit stats *fastq.gz`

file                                              |format|type|num_seqs|sum_len   |min_len|avg_len|max_len|Q1 |Q2 |Q3 |sum_gap|N50|Q20(%)|Q30(%)
:-------------------------------------------------|:-----|:---|:-------|:---------|:------|:------|:------|:--|:--|:--|:------|:--|:-----|:-----
reads/PRJNA295345/SRR2397934/SRR2397934_1.fastq.gz|FASTQ |DNA |5887653 |1750383981|32     |297.3  |301    |300|300|300|0      |300|97.29 |92.14
reads/PRJNA295345/SRR2397934/SRR2397934_2.fastq.gz|FASTQ |DNA |5887653 |1752648301|32     |297.7  |301    |300|300|301|0      |300|92.41 |83.08
reads/PRJNA295345/SRR2398152/SRR2398152_1.fastq.gz|FASTQ |DNA |5887653 |1750383981|32     |297.3  |301    |300|300|300|0      |300|97.29 |92.14
reads/PRJNA295345/SRR2398152/SRR2398152_2.fastq.gz|FASTQ |DNA |5887653 |1752648301|32     |297.7  |301    |300|300|301|0      |300|92.41 |83.08
reads/PRJNA295345/SRR2398177/SRR2398177_1.fastq.gz|FASTQ |DNA |5887653 |1750383981|32     |297.3  |301    |300|300|300|0      |300|97.29 |92.14
reads/PRJNA295345/SRR2398177/SRR2398177_2.fastq.gz|FASTQ |DNA |5887653 |1752648301|32     |297.7  |301    |300|300|301|0      |300|92.41 |83.08
reads/PRJNA295345/SRR2398282/SRR2398282_1.fastq.gz|FASTQ |DNA |5887653 |1750383981|32     |297.3  |301    |300|300|300|0      |300|97.29 |92.14
reads/PRJNA295345/SRR2398282/SRR2398282_2.fastq.gz|FASTQ |DNA |5887653 |1752648301|32     |297.7  |301    |300|300|301|0      |300|92.41 |83.08
reads/PRJNA295345/SRR2398314/SRR2398314_1.fastq.gz|FASTQ |DNA |5887653 |1750383981|32     |297.3  |301    |300|300|300|0      |300|97.29 |92.14
reads/PRJNA295345/SRR2398314/SRR2398314_2.fastq.gz|FASTQ |DNA |5887653 |1752648301|32     |297.7  |301    |300|300|301|0      |300|92.41 |83.08

When I tried `diff` in some subsets of the files I got that are effectively the same sequences in different files, so it seems understandable why  I got exactly the same microbial composition for every sample:

```bash
diff -y --suppress-common-lines SRR2397934_1.head SRR2398282_1.head | head
@SRR2397934.1 1 length=92                                     | @SRR2398282.1 1 length=92
+SRR2397934.1 1 length=92                                     | +SRR2398282.1 1 length=92
@SRR2397934.2 2 length=301                                    | @SRR2398282.2 2 length=301
+SRR2397934.2 2 length=301                                    | +SRR2398282.2 2 length=301
@SRR2397934.3 3 length=35                                     | @SRR2398282.3 3 length=35
+SRR2397934.3 3 length=35                                     | +SRR2398282.3 3 length=35
@SRR2397934.4 4 length=291                                    | @SRR2398282.4 4 length=291
+SRR2397934.4 4 length=291                                    | +SRR2398282.4 4 length=291
@SRR2397934.5 5 length=301                                    | @SRR2398282.5 5 length=301
+SRR2397934.5 5 length=301                                    | +SRR2398282.5 5 length=301
```

![level-7-bars](https://user-images.githubusercontent.com/12502882/63393141-bb300b00-c387-11e9-82f5-c477419d763b.png)

So that's it, I've been really confused about this the whole afternoon. What do you think?

**Comment by AstrobioMike** [comment]
Hi there!

Sorry you've been messing with this trying to figure it out! It is messed up. Each one of those holds ALL of the samples mixed together. So you can just pull any one of them, and then demultiplex that one into all the samples. The [biosample data](https://www.ncbi.nlm.nih.gov/biosample?Db=biosample&DbFrom=bioproject&Cmd=Link&LinkName=bioproject_biosample&LinkReadableName=BioSample&ordinalpos=1&IdsFromResult=295345) holds the barcodes for each individual sample, e.g. blank-4 is GAGTTGAG. I screwed up uploading this, was my first time :) I tried to sort it out a while back and gave up. You can get them all in a file from that page like so: 

![image](https://user-images.githubusercontent.com/13923308/63394805-34266700-c376-11e9-9061-4fdb14b25e41.png)

Then some bash magic will turn that into a cleaner mapping file, here's one kinda ugly example if you're newer to that side of things :) 

```
paste <(grep "Identifiers" biosample_result.txt | cut -f 4 -d ":" | cut -f 1 -d ";" | cut -c 2-) <(grep "barcode" biosample_result.txt | sed 's/^.*=//' | tr -d '"') | tr -d '*' > map.tsv
```

**Comment by AstrobioMike** [comment]
Actually you look pretty comfortable with bash already, so forget all that and just take the apology for the annoying archived data :/

**Comment by matrs** [comment]
I see, I was thinking about the size of each archive, I don't have much experience with amplicon data obviously but I had seen way smaller archives before. I downloaded the files using cli clients and as soon as i got them I run cutadapt and other few steps so I didn't catch this "detail". Thanks for your very quick answer and for the free quality content you put on your website.
