### ISSUE TITLE
qiime2 and dada2. What is the difference between dada2 in qiime2 and dada2 as a standalone tool? 

### ISSUE THREAD

**Issue by ClaraChong** [AstrobioMike/AstrobioMike.github.io#12]
About amplicon sequencing that uses DADA2 in QIIME2 environment, I wonder is it actually generating ASVs or OTUs? Is that means that as long as I am using DADA2 (no matter where it is embedded) I am actually generating ans ASV table?

**Comment by AstrobioMike** [comment]
Hi there!

Yes if you’re using dada2 in qiime2, it’s still dada2 and creating ASVs :) 

Only difference is there may be some minor functionality available in dada2 as a standalone that might not be configurable or accessible when using dada2 within qiime2. There’s just an inherent sacrifice of some things when we wrap other tools in a more convenient fashion and integrate them with other things like qiime2 does. That more than likely wouldn’t be an issue though, or anything you’d necessarily need or notice :)
