### ISSUE TITLE
Bioconductor installation instructions

### ISSUE THREAD

**Issue by csoneson** [AstrobioMike/AstrobioMike.github.io#14]
**Describe the mistake, bug, or typo here:**
The installation instructions for Bioconductor packages are based on the `biocLite()` function. However, Bioconductor packages are currently installed via the `BiocManager` package, see https://www.bioconductor.org/install/

**Link to the page containing the issue:**
https://github.com/AstrobioMike/AstrobioMike.github.io/blob/master/R/installing_packages.md

**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
Update the Bioconductor installation instructions :)

**Comment by AstrobioMike** [comment]
Beautiful! Thanks so much, updated :) 

https://github.com/AstrobioMike/AstrobioMike.github.io/commit/f3cb1c619150dcd10f2b4a94f84dc502c13dc99f
