### ISSUE TITLE
hmm-sources-Campbell_et_al

### ISSUE THREAD

**Issue by Luyang-1987** [AstrobioMike/AstrobioMike.github.io#20]
sorry to bother, well, I have installed hmm with conda, but my hmm source only have Ribosomal_RNAs, Protista_83, Bacteria_71 and Archaea_76. I have no idea about how to add other sources like Campbell_et_al and some others to my local sources, so if could you give me some suggestions about this?

**Comment by AstrobioMike** [comment]
Hi there!

Thanks for noting, it's that that is using an older version of anvi'o and i really need to update. In the meantime, i certainly should add a note about that. Campbell_et_al was for bacteria, but now "Bacteria_71" is the one for it. So you should specify that one. 

Thanks for reminding me of this, and i will update the page(s) ASAP to note it :)

**Comment by AstrobioMike** [comment]
Thanks again for notifying me about this!
I added notes for now, but I hope to update these pages soon to be re-done with the latest version of anvi'o, as a lot's changed and been added. 

Cheers :)

**Comment by Luyang-1987** [comment]
thank you!  be eager for the latest version and the updated page
