### ISSUE TITLE
Mistake, bug, or typo

### ISSUE THREAD

**Issue by hoytpr** [AstrobioMike/AstrobioMike.github.io#23]
**Describe the mistake, bug, or typo here:**
Link to Slack channel at bottom of page not working. Error is:
'ZEIT Now 1.0 has been shut down. As part of this, all ZEIT Now 1.0 Deployments are now inaccessible.'

**Link to the page containing the issue:**
https://astrobiomike.github.io/unix/getting-started
At bottom of page 

**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
Not good enough to help. Just wanted you to know!

**Comment by AstrobioMike** [comment]
Ah thanks so much for letting me know! Should be fixed now :)
