### ISSUE TITLE
Mistake, bug, or typo

### ISSUE THREAD

**Issue by strayologist** [AstrobioMike/AstrobioMike.github.io#29]
![image](https://user-images.githubusercontent.com/46269216/118667720-de644480-b811-11eb-969f-fd54e62d08aa.png)

**Describe the mistake, bug, or typo here:**
I have attached the screenshot.

> If we want to append an output to a file, rather than overwrite it, we can use two of them instead, >>:

After this line the code is:
`ls >> directory_contents.txt`

I think after `ls`, there should be a directory name because what else is this code appending? 
I'm very new to this, sorry if I'm wrong.

**Link to the page containing the issue:**
https://astrobiomike.github.io/unix/wild-redirectors#redirectors-and-wildcards

**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
Just adding `experiment/` before `>>`  would suffice, I think.

**Comment by AstrobioMike** [comment]
Hi there!

Thanks for writing in :) 

So when we run `ls` by itself (with no other arguments), it runs on the current directory we are sitting in. So when we do `ls >> directory_contents.txt`, we are adding the output from `ls` (which just lists the stuff that's in the directory we are sitting in) to the text file called `directory_contents.txt`. 

Does that make sense?

**Comment by strayologist** [comment]
Okay, understood! 
Thanks for the explanation. 🙂
