### ISSUE TITLE
[JOSE Review] General Comments

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [AstrobioMike/AstrobioMike.github.io#3]
Nice work! Here are some overall feedback: 

No where is it clear where to ask for help. It's probably unrealistic for you to 
provide a high-level of support for a site like this, but some links and explanation
about resources like [Biostars](https://www.biostars.org/), StackOverflow, etc. 
would be a reasonable support option. 

BASH and R lessons would benefit from some "thought" questions (i.e. what do you 
think this does? What might happen if we try?). I think these two sections have 
very helpful content, but to satisfy the pedagogical requirements of publication, 
these sections need some clear statements of intended learning outcomes and 
clear questions (summative and if possible formative) to help a learner self-assess. 
Learners need to test to see if they understand a concept, and if they aren't understanding
they should get some clues on where to look if additional explanation 
is needed. 

There should be some explanation that the BASH and R sections are suited for novice 
learners and that while these lessons may better help a learner understand the 
Amplicon Analysis and Genomics tutorials, there is still a large learning gap 
between those intros and full workflows.  

Learning objectives are implicit in some places, but they could be more clearly stated. 
Tutorials are thoroughly work, but without any kinds of formative assessments, 
it may be difficult for learners to transfer their understanding to a situation outside 
the context of the tutorial.

**Comment by AstrobioMike** [comment]
Thanks, Jason! 

I’ve specifically added biostars and stackoverflow to the [other great resources page](https://astrobiomike.github.io/unix/other_resources).

I've actually been in the process of converting my bash stuff into more of a teaching format for the [DIBSI course at UCDavis](http://ivory.idyll.org/dibsi/ANGUS.html) this summer (including smaller blocks of things and interim challenge questions), and have been toying with the idea of overhauling my site's area to be what I've put together for that. So this finally pushed me over the edge to do that :) 

So now the bash section has an explicit [crash course/intro laid out here](https://astrobiomike.github.io/unix/unix-intro) with 5 smaller blocks, and challenge questions interspersed in collapsible boxes. E.g. scroll down about half a page from here: [https://astrobiomike.github.io/unix/wild-redirectors#wildcards](https://astrobiomike.github.io/unix/wild-redirectors#wildcards). And have also cleaned up and added some to the R section, e.g. down a bit from here: [https://astrobiomike.github.io/R/basics#variables-in-r](https://astrobiomike.github.io/R/basics#variables-in-r).

I've also added more "Things covered here" boxes at the top of each unix lesson (e.g. [https://astrobiomike.github.io/unix/getting-started](https://astrobiomike.github.io/unix/getting-started), as well as to the [intro to R page](https://astrobiomike.github.io/R/basics). 

Thanks for taking your time to look things over and provide feedback :)

**Comment by JasonJWilliamsNY** [comment]
Awesome - thanks for doing and sharing this!
