### ISSUE TITLE
New Topic Idea

### ISSUE THREAD

**Issue by strayologist** [AstrobioMike/AstrobioMike.github.io#30]
![image](https://user-images.githubusercontent.com/46269216/118687594-d3fe7680-b822-11eb-9057-add51659afbb.png)

**What else do you think should be covered on the site?** (This can be a request for something you are or did have trouble with, or it can be a suggestion for something you're comfortable with but think will help others!)

I would suggest adding this code snippet at the end so that the person can see the result of replacing \r with \n. 
`wc -l gene_annotations_fixed.tsv`

Page link: https://astrobiomike.github.io/unix/six-glorious-commands#tr

**Comment by AstrobioMike** [comment]
Thanks for the suggestion! Added it in 👍

**Comment by strayologist** [comment]
Awesome! Thank you. 🙂
