### ISSUE TITLE
Error in installing sabre

### ISSUE THREAD

**Issue by charles7007** [AstrobioMike/AstrobioMike.github.io#31]
Hi, I am trying to demultiplex on my metabarcoding data. I found that  "sabre" can do it. I have try to install sabre, but face some problem with installing. Hoping for a guide from you all to me to solve the problem. 

-------------------------------------------------------------------------------------------------------------------------------
It shows an error at the step "make" file.

![1](https://user-images.githubusercontent.com/84772668/119472498-e0cc1e80-bd7c-11eb-9a2f-b810deea5431.png)

**Comment by AstrobioMike** [comment]
Hey there, Charles!

I see you have conda setup. Have you tried a conda install for sabre? E.g.:

```
conda install -c conda-forge -c bioconda -c defaults sabre
```

**Comment by charles7007** [comment]
> Hey there, Charles!
> 
> I see you have conda setup. Have you tried a conda install for sabre? E.g.:
> 
> ```
> conda install -c conda-forge -c bioconda -c defaults sabre
> ```

**Comment by charles7007** [comment]
> > Hey there, Charles!
> > I see you have conda setup. Have you tried a conda install for sabre? E.g.:
> > ```
> > conda install -c conda-forge -c bioconda -c defaults sabre
> > ```

Thank you, Mike. I did it! Finally, I can run it.
