### ISSUE TITLE
[JOSE Review] Community contribution requirement

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [AstrobioMike/AstrobioMike.github.io#4]
There are links on the rendered page suggesting users can create issues. There 
could be some template instructions in the issue and GitHub has features to 
support this (e.g. https://help.github.com/en/articles/setting-guidelines-for-repository-contributors).

**Comment by AstrobioMike** [comment]
Love it! Didn't realize it was so easy to set these up :) 

https://github.com/AstrobioMike/AstrobioMike.github.io/issues/new/choose
