### ISSUE TITLE
Support for SILVA v138.1

### ISSUE THREAD

**Issue by Anto007** [AstrobioMike/AstrobioMike.github.io#43]
I'm new to this sort of analysis and thanks a zillion for this excellent tutorial! I was wondering if you could perhaps include steps to use the latest version of silva database (v138.1) since this database version doesn't seem to be made available on DECIPHER. I did the below instead of DECIPHER but (obviously) the rest of your R command-lines then break. Perhaps this is too much to ask but I would appreciate any quick-fix ideas you might have. Also, I'm a newbie to R which is not helping with things here either. 

```
tax_info <- assignTaxonomy(seqtab.nochim, "/home/cvb/tools/dada2_db/silva_nr99_v138.1_train_set.fa", multithread=TRUE); save.image(file="tax-info.RData")
load("tax-info.RData")
```

Specifically, the below is what breaks

```
asv_tax <- t(sapply(tax_info, function(x) {
  m <- match(ranks, x$rank)
  taxa <- x$taxon[m]
  taxa[startsWith(taxa, "unclassified_")] <- NA
  taxa
}))
Error in x$rank : $ operator is invalid for atomic vectors
```

**Comment by AstrobioMike** [comment]
Hey there, @Anto007 :) 

Thanks for the kind words! So glad it's been helpful at all :)

I wrote the DECIPHER developer asking if they had documented how they made the previous one, and if/when I hear back, I'll see about creating an updated DECIPHER-formatted SILVA 138.1 👍 

In the meantime, to move forward with the dada2 classification output like you've generated above, i believe this will work to get you to the standard table I produce in the tutorial, taking off from the `tax_info` object you created above:

```R
# loading your tax info saved data from your run
load("tax-info.RData")

# making an object we are going to modify, to leave the initial tax_info object alone
asv_tax <- tax_info

# adding the ASV IDs as row names (this asv_headers object should exist from the tutorial already)
row.names(asv_tax) <- sub(">", "", asv_headers)

# and that looks like this (with the tutorial data, not yours, just showing the format)
head(asv_tax)
```

```
      Kingdom    Phylum           Class                 Order                   Family           Genus       
ASV_1 "Bacteria" "Proteobacteria" "Alphaproteobacteria" "Kordiimonadales"       NA               NA          
ASV_2 "Bacteria" "Nitrospirota"   "Nitrospiria"         "Nitrospirales"         "Nitrospiraceae" "Nitrospira"
ASV_3 "Bacteria" "Proteobacteria" "Alphaproteobacteria" "Kiloniellales"         "Kiloniellaceae" NA          
ASV_4 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "pItb-vmat-80"          NA               NA          
ASV_5 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "UBA10353 marine group" NA               NA          
ASV_6 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Steroidobacterales"    "Woeseiaceae"    "Woeseia" 
```

I'm not sure if the column headers would be a problem with anything else in the tutorial, but just to be sure, we can change them to what I have:

```R
colnames(asv_tax) <- c("domain", "phylum", "class", "order", "family", "genus")

head(asv_tax)
```

```
      domain     phylum           class                 order                   family           genus       
ASV_1 "Bacteria" "Proteobacteria" "Alphaproteobacteria" "Kordiimonadales"       NA               NA          
ASV_2 "Bacteria" "Nitrospirota"   "Nitrospiria"         "Nitrospirales"         "Nitrospiraceae" "Nitrospira"
ASV_3 "Bacteria" "Proteobacteria" "Alphaproteobacteria" "Kiloniellales"         "Kiloniellaceae" NA          
ASV_4 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "pItb-vmat-80"          NA               NA          
ASV_5 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "UBA10353 marine group" NA               NA          
ASV_6 "Bacteria" "Proteobacteria" "Gammaproteobacteria" "Steroidobacterales"    "Woeseiaceae"    "Woeseia"
```

Be aware, this tax stops at genus level, and the DECIPHER tax stops at species. So this table is still slightly different. I don't think that will make you run into a code problem elsewhere or not in the tutorial, but happy to try to help again if you do :)

Let me know if that works for you!

**Comment by Anto007** [comment]
Thank you very much for your kind response. Your suggestions worked like a charm! Thanks again for being such a kind soul always in this heartless world of academia :-)
