### ISSUE TITLE
Deseq error

### ISSUE THREAD

**Issue by XELong** [AstrobioMike/AstrobioMike.github.io#56]
**Describe the mistake, bug, or typo here:**
Error in DESeqDataSetFromMatrix(count_tab, colData = sample_info_tab,  :
 ncol(countData) == nrow(colData) is not TRUE
**Link to the page containing the issue:**
Line 290 deseq_counts <- DESeqDataSetFromMatrix(count_tab, colData = sample_info_tab, design = ~type) 
**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
Dear AstrobioMike，
         Here, I got another error in running my own data. I had search for an answer. However, I still don't know why for I just followed the codes of the tutorial. It was no problem for your data. 
![sample_info_tab](https://user-images.githubusercontent.com/63763606/202378043-0d71f904-b06c-42f8-a87a-ea96be4490a8.png)This is my sample_info_tab
![count_tab](https://user-images.githubusercontent.com/63763606/202378146-14b82ee0-c94f-43bc-bb47-60021c5690fc.png)
This is my count_tab
The answer for a similar problem like this : 
colData should contain a row for each sample in the analysis, which countData should contain one column for each sample. Therefore the number of rows in colData should be the same as the number of columns in countData and both should be equal to the number of samples in the study. https://www.biostars.org/p/418963/#418964
I don't know how to fix this error.
Thank  you very much!

Best wishes

Long

**Comment by AstrobioMike** [comment]
Hi there, Long,

It seems like the rows in the sample info table are not matching up with the columns in the count table. I don't know where that would have happened in your processing. The preview images of each looks like one of them starts with S01 and the other starts with S05. So maybe you dropped some from the count table? There is code in the tutorial that drops 4 "blanks" I think, maybe you did something like that. You just have to find where you dropped those samples. You have to explore the tables more closely. Use things like `dim(sample_info_table)` and `row.names(sample_info_table)`, and compare that to what you get from `dim(count_tab)` and `col.names(count_tab)`. 

Check those all throughout your R code from the start and find where they diverge. 

Good luck!

**Comment by XELong** [comment]
Yes!!! The tutorial had remove the first four column for further analysis by the following step!
count_tab <- read.table("ASVs_counts-no-contam.tsv", header=T, row.names=1,
                        check.names=F, sep="\t")[ , -c(1:4)]
