### ISSUE TITLE
Nano issue

### ISSUE THREAD

**Issue by TylerC0** [AstrobioMike/AstrobioMike.github.io#59]
Hello Mike,

Firstly, I would like to say thank you for the tutorials! They are very helpful. As for what I have noticed, loading the link to the Binder on the page for "An introduction for Scripting", nano is not pre-loaded into the terminal. This means that you cannot proceed with the tutorial. I have tried looking up how to install nano in the notebook, but have had no luck so if it is something I am doing , please let me know! The error is: bash: nano command not found

**Link to the page containing the issue:**
https://astrobiomike.github.io/unix/scripting#binder-available

**Suggested fix – if any, just reporting what's wrong is super-helpful either way :)**
 I have been coming back on-and-off when I do these lessons, so each time I would go to a previous page to load the Binder, which solves the issues as nano is installed on the other links prior to this, such as this one https://astrobiomike.github.io/unix/getting_unix_env

**Comment by AstrobioMike** [comment]
thanks for the kind words and note, @TylerC0! I for sure accidentally linked to the wrong binder, it's updated now to point to the same ones as the unix-intro like you found to be working 👍 

thanks again!
