### ISSUE TITLE
[JOSE Review] R lessons

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [AstrobioMike/AstrobioMike.github.io#6]
R Basics, 

Might it be a good idea to have screenshots of the RStudio Environment
(Consider using RStudio cloud? or a VM). Would a short video help here? 
For example, people can use CyVerse VICE (a project I work on) to 
launch Jupyter/RStudio/RShiny environments. It's still in its first release 
but I think is working pretty well. Would be happy to share talk if 
there is interest in setting this up for you. (Follow up: I see in the 
DADA2 lesson you use Binder to launch RStudio, so maybe here too?)

Although RStudio is recommended, its not clear why since the tutorial does 
not really cover the value-add of the RStudio environment. 

DataCamp is listed as a recommendation for future learning. It is your choice on 
what to recommend, but some have withdrawn recommendation due to 
their handling of misconduct: https://carpentries.org/blog/2019/04/datacamp-response/ 

R Installing Packages
Bioconductor is mentioned later in the text, but there is not much of an introduction to it. Maybe a few sentences to make the concept clear (perhaps starting from your introduction
when you mention CRAN) that these are good places to search for packages.

**Comment by AstrobioMike** [comment]
Stellar! Added in a binder for [this lesson](https://astrobiomike.github.io/R/basics) and re-did the entire page cleaning some things up and changing all images to be taken from the binder environment.

I forgot i had datacamp recommended in there :/ I did learn a lot from them, but i definitely don't feel comfortable promoting them currently either, so thanks for pointing that out. I removed it.

And I added to the intro at the top that part of the power/value of R is all of the open-source tools people build for it and link to the [installing packages page](https://astrobiomike.github.io/R/installing_packages) noting that it covers some of typical avenues and hiccups of installing packages, and listed CRAN and Bioconductor at the top of that page  :) 

(I didn't realize i had noted up there I'd be covering that in this page still, even though i ended up moving it to its own to keep it separate from the fundamentals of R. Thanks for catching that!)
