### ISSUE TITLE
[JOSE Review] DADA2 Full example workflow

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [AstrobioMike/AstrobioMike.github.io#7]
You have a for loop in your example. Previous commands work well with copy/paste. 
Since this one does not - perhaps some explanation to the learner about formatting?

**Comment by AstrobioMike** [comment]
Did copy and paste not work for you on this? I don't have a problem with it and can't seem to recreate a problem. 

I also don't know if you noticed, but i have a "note" box above it explaining this page isn't for getting into loops but if unfamiliar with them to visit [the wonderful world of loops page](https://astrobiomike.github.io/bash/for_loops). Do you still think just a few sentences would be helpful here? 

Thanks :)

**Comment by JasonJWilliamsNY** [comment]
When I tried copying/pasting it did not work. Maybe just a note that things need to be properly indented and your link to the reference?

**Comment by AstrobioMike** [comment]
Hmm, i'm not sure what's going on. But indentation or spacing in a bash loop actually doesn't matter (unlike python and some other languages), and testing I can copy and paste just fine with or without the indenting:

![image](https://user-images.githubusercontent.com/13923308/59702302-3b7d9880-91ac-11e9-9308-e23cacb1cb70.png)

![image](https://user-images.githubusercontent.com/13923308/59702323-4afce180-91ac-11e9-849d-06ea1f042a60.png)

If you were working on something other than the binder environment, if you can, can you send me the outputs to `echo $0` and `bash --version` so maybe i can better track down when this is a problem and figure out what's going on? 

It's definitely meant to be copy-and-pastable, i for sure don't mean to leave anyone hanging having to type that out by eye!

Thanks :)

**Comment by JasonJWilliamsNY** [comment]
I was using the binder environment provided in the example (specifically RStudio terminal). I tried all this again and it worked so I must have been having a bad copy/paste day!
