### ISSUE TITLE
[JOSE Review] de novo genome assembly 

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [AstrobioMike/AstrobioMike.github.io#8]
Providing a VM/Binder/etc. would be helpful. I know these can take time to get
setup and working correctly. Perhaps a simpler alternative would be 
showing how these tools could be installed using [Bioconda](https://bioconda.github.io/])?
I see you use it in the MAGs lesson

**Comment by AstrobioMike** [comment]
Thanks for all the suggestions/tips, @JasonJWilliamsNY! Working my way through :) As I think you saw them later, i've been slowly implementing binder environments as I can. Like for the [bash intro](https://astrobiomike.github.io/bash/bash_intro_binder#accessing-our-command-line-environment) and [amplicon workflow](https://astrobiomike.github.io/amplicon/dada2_workflow_ex#binder-available). And have desperately been wanting to overhaul program installation all around to the wonderful world of conda. What better time to get to it finally than now :)

For this one, i've added a [conda environment setup](https://astrobiomike.github.io/genomics/de_novo_assembly#conda-installations), and updated the page to the latest version of anvi'o as it has changed quite a bit, as did some of the commands.

Thanks again, and i'll keep chugging through your much appreciated input!
